
author:
    - name: Robert Duncan
      email: duncanrm2@vcu.edu

date: 4/29/25

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
